python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 4096
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 8192
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 12288
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 16384
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 20480
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 24576
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 28672
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 32768
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 36864
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 40960
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 45056
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 49152
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 53248
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 57344
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 61440
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 1 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 65536
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 4096
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 8192
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 12288
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 16384
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 20480
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 24576
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 28672
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 32768
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 36864
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 40960
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 45056
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 49152
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 53248
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 57344
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 61440
sleep 1
python3 -m torch.distributed.launch --nnodes 1 --nproc_per_node 1 train_dist_random.py --set_experts_manually 0 --profile_mode sequence --shape_order SBH --profile_unit attention --model_size qwen2.5-72b --hidden_size 1024 --num_attention_heads 8 --vocab_size 152064 --max_predictions_per_seq 20 --set_model_config_manually 0 --set_layernum_manually 1 --set_seqlen_manually 1 --global_train_batch_size 1 --epochs 10 --lr 0.0001 --adam_weight_decay 0.01 --dropout_prob 0.1 --check_loss 0 --profile 1 --save_profiled_memory 0 --profile_forward 1 --initialize_on_meta 1 --global_tp_consec 1 --sdp 0 --chunks 1 --pipeline_type gpipe --default_dp_type ddp --mixed_precision bf16 --shape_order SBH --num_hidden_layers 2 --pp_deg 1 --global_tp_deg 1 --global_cp_deg 1 --global_checkpoint 0 --seq_length 65536
sleep 1
